---
title: "Scraping through the Billboard Website"
author: "Johan Hamsa & Ishaan Gupta"
date: "`r format(Sys.Date(), '%A, %B %e %Y')`"
output: 
  html_document: default 
  pdf_document: default
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  echo = TRUE,
  eval = TRUE,
  message = FALSE,
  warning = TRUE)

```

# Loading the r packages 

```{r pcks, echo = FALSE}

library(tidyverse)
library(rvest)
library(polite)
library(stringr)
library(dplyr)

```

# Retrieving the Billboard Hot 100 data 

```{r billboard-hot-100-function}

top_singles <- function(year){
  
  rank <- bow(
    str_c("https://www.billboard.com/charts/year-end/", year ,"/hot-100-songs")
    ) %>% 
    scrape() %>% 
    html_nodes(".ye-chart-item__rank") %>% 
    html_text %>% 
    as.numeric()
  
  titles <- bow(
    str_c("https://www.billboard.com/charts/year-end/", year ,"/hot-100-songs")
    ) %>% 
    scrape() %>% 
    html_nodes(".ye-chart-item__title") %>% 
    html_text %>% 
    str_remove_all("\\n")
  
  artists <- bow(
    str_c("https://www.billboard.com/charts/year-end/", year ,"/hot-100-songs")
    ) %>% 
    scrape() %>% 
    html_nodes(".ye-chart-item__artist") %>% 
    html_text %>% 
    str_remove_all("\\n") 
  
tibble(Rank = rank,
       Title = titles, 
       Artist = artists,
       Year = year,
       Points = 101.00 - Rank)

}

```

```{r billboard-hot-100}

hot_100 <- 
 map_dfr(2010:2019, top_singles)

```

# Retrieving the Billboard Top Albums data 

```{r billboard-top-albums-function}

top_albums <- function(year){
  
  rank <- bow(
       str_c("https://www.billboard.com/charts/year-end/", year, "/top-billboard-200-albums")
       ) %>% 
    scrape() %>% 
    html_nodes(".ye-chart-item__rank") %>% 
    html_text() %>% 
    as.numeric
  
  albums <- bow(
    str_c("https://www.billboard.com/charts/year-end/", year, "/top-billboard-200-albums")
    ) %>% 
    scrape() %>% 
    html_nodes(".ye-chart-item__title") %>% 
    html_text() %>% 
    str_remove_all("\\n")
  
  artists <- bow(
    str_c("https://www.billboard.com/charts/year-end/", year, "/top-billboard-200-albums")
    ) %>% 
    scrape() %>% 
    html_nodes(".ye-chart-item__artist") %>% 
    html_text() %>% 
    str_remove_all("\\n")
  
  tibble(Rank = rank,
         Album = albums, 
         Artist = artists,
         Year = year,
         Points = (201 - Rank)/2)
}

```

```{r billboard-top-albums}

albums <- 
  map_dfr(2010:2019, top_albums)

```

# Retrieving the Billboard Top Streaming songs data 

```{r billboard-streaming-function}

top_streams <- function(year){
  
  position <- bow(str_c("https://www.billboard.com/charts/year-end/", year ,"/streaming-songs"))%>% 
    scrape() %>% 
    html_nodes(".ye-chart-item__rank") %>% 
    html_text %>% 
    as.numeric()
  
  titles <- bow(str_c("https://www.billboard.com/charts/year-end/", year ,"/streaming-songs"))%>% 
    scrape() %>% 
    html_nodes(".ye-chart-item__title") %>% 
    html_text %>% 
    str_remove_all("\\n")
  
  artists <- bow(str_c("https://www.billboard.com/charts/year-end/", year ,"/streaming-songs"))%>%  
    scrape() %>% 
    html_nodes(".ye-chart-item__artist") %>% 
    html_text %>% 
    str_remove_all("\\n") 
  
tibble(Rank = position,
       Title = titles, 
       Artist = artists,
       Year = year,
       Points = (76 - Rank)/0.75)

}
```

```{r billboard-streams}

streams <- 
  map_dfr(2010:2019, top_streams)

```

# Retrieving the Billboard Top Radio Songs data 

```{r billboard-radio-function}

top_radio <- function(year){
  
  position <- bow(str_c("https://www.billboard.com/charts/year-end/", year ,"/radio-songs"))%>% 
    scrape() %>% 
    html_nodes(".ye-chart-item__rank") %>% 
    html_text %>% 
    as.numeric()
  
  titles <- bow(str_c("https://www.billboard.com/charts/year-end/", year ,"/radio-songs"))%>% 
    scrape() %>% 
    html_nodes(".ye-chart-item__title") %>% 
    html_text %>% 
    str_remove_all("\\n")
  
  artists <- bow(str_c("https://www.billboard.com/charts/year-end/", year ,"/radio-songs"))%>%  
    scrape() %>% 
    html_nodes(".ye-chart-item__artist") %>% 
    html_text %>% 
    str_remove_all("\\n") 
  
tibble(Rank = position,
       Title = titles, 
       Artist = artists,
       Year = year,
       Points = (76 - Rank)/0.75)

}
```

```{r billboard-radio}

radio <- 
  map_dfr(2010:2019, top_radio)

```

# Retrieving the Billboard Top Digital Song Sales data 

```{r billboard-digital-sales-function}

top_digital <- function(year){
  
  position <- bow(str_c("https://www.billboard.com/charts/year-end/", year ,"/digital-songs"))%>% 
    scrape() %>% 
    html_nodes(".ye-chart-item__rank") %>% 
    html_text %>% 
    as.numeric()
  
  titles <- bow(str_c("https://www.billboard.com/charts/year-end/", year ,"/digital-songs"))%>% 
    scrape() %>% 
    html_nodes(".ye-chart-item__title") %>% 
    html_text %>% 
    str_remove_all("\\n")
  
  artists <- bow(str_c("https://www.billboard.com/charts/year-end/", year ,"/digital-songs"))%>%  
    scrape() %>% 
    html_nodes(".ye-chart-item__artist") %>% 
    html_text %>% 
    str_remove_all("\\n") 
  
tibble(Rank = position,
       Title = titles, 
       Artist = artists,
       Year = year,
       Points = (76 - Rank)/0.75)

}
```

```{r billboard-digital-sales}

digital_sales <- 
  map_dfr(2010:2019, top_digital)

```

# Creating the csv files

```{r write-csv, eval = FALSE}

write.csv(hot_100, file = "data/hot_100.csv", row.names = FALSE) 
write.csv(albums, file = "data/albums.csv", row.names = FALSE)
write.csv(digital_sales, file = "data/digital_sales.csv", row.names = FALSE)
write.csv(radio, file = "data/radio.csv", row.names = FALSE)
write.csv(streams, file = "data/streams.csv", row.names = FALSE)
              
```
